# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: remove-crlf
      - id: remove-tabs
        args: [ '--whitespaces-count', '2' ]  # defaults to: 4

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.16.0
    hooks:
      - id: gitlint

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.6.0
    hooks:
      - id: check-jsonschema
        name: "Check GitHub Workflows"
        language: python
        files: ^\.github/workflows/
        types: [yaml]
        args: ["--schemafile", "https://json.schemastore.org/github-workflow"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-java
    rev: 1.3.10
    hooks:
      - id: validate-html

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
    hooks:
      - id: htmllint

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.2.0'
    hooks:
      - id: eslint

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: '0.0.2'
    hooks:
      - id: stylelint
        additional_dependencies: ['stylelint@14.0.1', 'stylelint-config-recommended@6.0.0']

  - repo: https://github.com/Lucas-C/pre-commit-hooks-lxml
    rev: 'v1.1.0'
    hooks:
      - id: forbid-html-img-without-alt-text
      - id: detect-missing-css-classes
        args:
          - --css-files-dir
          - css
          - --html-files-dir
          - html
      - id: html-tags-blacklist
      - id: html-attributes-blacklist
